[platformio]
default_envs = tracker_v2_full

[env]
platform = espressif32@7.0.1
board = heltec_wireless_tracker_v2
framework = arduino
board_build.variants_dir = variants
board_build.variant = tracker_v2
monitor_speed = 115200
monitor_dtr = 0
monitor_rts = 0
build_src_filter = +<*> -<tasks/ButtonTask.cpp> -<tasks/CountDownTimer.cpp>
lib_ldf_mode = chain+
build_flags =
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D WIRELESS_TRACKER_V2
    -D USE_KCT8103L_PA
lib_deps =
    https://github.com/HelTecAutomation/Heltec_ESP32.git#55bf1a5fe0ed102c807b1fcb550a1a8ea31d6bd3
    knolleary/PubSubClient
    bblanchon/ArduinoJson
    adafruit/Adafruit GFX Library
    inflop/Countimer@^1.0.0
    mathertel/LiquidCrystal_PCF8574@^2.2.0
    jgromes/RadioLib@7.7.1
    sparkfun/SparkFun BMI270 Arduino Library @ ^1.0.3

[env:tracker_v2_gps]
build_flags = ${env.build_flags} -D TRACKER_STAGE=1

[env:tracker_v2_lora]
build_flags = ${env.build_flags} -D TRACKER_STAGE=2

[env:tracker_v2_tft]
build_flags = ${env.build_flags} -D TRACKER_STAGE=3

[env:tracker_v2_full]
build_flags = ${env.build_flags} -D TRACKER_STAGE=4
